
import { Sneaker, Post, ToastMessage, Badge, LeaderboardUser, Conversation, Story, Retailer } from './types';

export const APP_VERSION = '1.0.0 (Launch Day)';

export const NEWS_TICKER = [
  "BREAKING: Jordan 1 'Lost & Found' Restock Rumored for 3 PM EST",
  "MARKET UPDATE: Yeezy Slides up 15% this week",
  "LEAK: Travis Scott x Nike Mac Attack official images loaded",
  "REMINDER: SNKRS Draw for Dunk Low 'Panda' opens in 1 hour",
  "INDUSTRY: Adidas CEO steps down, stock plummets"
];

export const BADGES: Badge[] = [
  { id: '1', icon: '👑', label: 'OG Member', description: 'Joined during Beta', color: 'bg-amber-500/20 text-amber-500 border-amber-500' },
  { id: '2', icon: '💎', label: 'Diamond Hands', description: 'Portfolio value > $1k', color: 'bg-cyan-500/20 text-cyan-500 border-cyan-500' },
  { id: '3', icon: '🔥', label: 'Hypebeast', description: 'Copped 5+ Hype items', color: 'bg-red-500/20 text-red-500 border-red-500' },
  { id: '4', icon: '🤖', label: 'Bot Slayer', description: 'Beat the bots manually', color: 'bg-violet-500/20 text-violet-500 border-violet-500' },
];

export const MOCK_LEADERBOARD: LeaderboardUser[] = [
  { rank: 1, username: 'KicksKing_99', avatar: 'https://ui-avatars.com/api/?name=Kicks+King&background=F59E0B&color=fff', portfolioValue: 45200, change: 12.5 },
  { rank: 2, username: 'SoleSurvivor', avatar: 'https://ui-avatars.com/api/?name=Sole+Survivor&background=10B981&color=fff', portfolioValue: 38900, change: 8.2 },
  { rank: 3, username: 'HypeBeast_X', avatar: 'https://ui-avatars.com/api/?name=Hype+Beast&background=8B5CF6&color=fff', portfolioValue: 29500, change: -2.1 },
];

export const MOCK_NOTIFICATIONS = [
  { id: '1', title: 'Shock Drop Alert', message: 'Travis Scott Olive just shock dropped on SNKRS!', time: '2m ago', read: false },
  { id: '2', title: 'Price Change', message: 'Jordan 1 Lost & Found resale dropped by $20.', time: '1h ago', read: false },
  { id: '3', title: 'Restock', message: 'Nike Dunk Low Panda restocked at Foot Locker.', time: '3h ago', read: true },
];

export const MOCK_STORIES: Story[] = [
  { id: 's1', user: 'SneakPeak', avatar: 'https://cdn-icons-png.flaticon.com/512/2589/2589903.png', image: 'https://picsum.photos/seed/s1/400/800', title: 'Weekly Recap', viewed: false },
  { id: 's2', user: 'Nike', avatar: 'https://ui-avatars.com/api/?name=Nike&background=000&color=fff', image: 'https://picsum.photos/seed/s2/400/800', title: 'SNKRS Day', viewed: false },
  { id: 's3', user: 'Kith', avatar: 'https://ui-avatars.com/api/?name=Kith&background=fff&color=000', image: 'https://picsum.photos/seed/s3/400/800', title: 'New Lookbook', viewed: true },
  { id: 's4', user: 'Yeezy', avatar: 'https://ui-avatars.com/api/?name=Yeezy&background=555&color=fff', image: 'https://picsum.photos/seed/s4/400/800', title: 'Archive Drop', viewed: false },
];

export const MOCK_CONVERSATIONS: Conversation[] = [
  {
    id: 'c1',
    withUser: 'J23_Official',
    userAvatar: 'https://ui-avatars.com/api/?name=J+23&background=ef4444&color=fff',
    lastMessage: 'Would you take $350 for the Lost & Founds?',
    unread: 2,
    messages: [
      { id: 'm1', sender: 'other', text: 'Yo, nice collection.', timestamp: '10:00 AM', type: 'text' },
      { id: 'm2', sender: 'me', text: 'Thanks bro! Trying to build it up.', timestamp: '10:05 AM', type: 'text' },
      { id: 'm3', sender: 'other', text: 'Would you take $350 for the Lost & Founds?', timestamp: '10:15 AM', type: 'text' }
    ]
  },
  {
    id: 'c2',
    withUser: 'ResellGod',
    userAvatar: 'https://ui-avatars.com/api/?name=Resell+God&background=10b981&color=fff',
    lastMessage: 'Trade Offer Sent',
    unread: 0,
    messages: [
      { id: 'm1', sender: 'me', text: 'Still have the Travis Scotts?', timestamp: 'Yesterday', type: 'text' },
      { id: 'm2', sender: 'other', text: 'Yeah but only looking for trades.', timestamp: 'Yesterday', type: 'text' }
    ]
  }
];

export const DEFAULT_RETAILERS: Retailer[] = [
  { id: 'sx', name: 'StockX', baseUrl: 'https://stockx.com/search?s=', affiliateParam: '&utm_source=SneakPeak', color: 'text-green-500', bg: 'bg-green-900/20', abbr: 'SX' },
  { id: 'gt', name: 'GOAT', baseUrl: 'https://www.goat.com/search?query=', affiliateParam: '', color: 'text-blue-500', bg: 'bg-blue-900/20', abbr: 'GO' },
  { id: 'eb', name: 'eBay Sneakers', baseUrl: 'https://www.ebay.com/sch/i.html?_nkw=', affiliateParam: '', color: 'text-yellow-500', bg: 'bg-yellow-900/20', abbr: 'EB' },
  { id: 'fl', name: 'Foot Locker', baseUrl: 'https://www.footlocker.com/search?query=', affiliateParam: '', color: 'text-red-500', bg: 'bg-red-900/20', abbr: 'FL' },
];

export const MOCK_SNEAKERS: Sneaker[] = [
  {
    id: '1',
    name: 'Air Jordan 1 High OG "Lost & Found"',
    brand: 'Jordan',
    price: 180,
    image: 'https://picsum.photos/seed/jordan1/800/800',
    dropDate: new Date(Date.now() + 86400000 * 2).toISOString(),
    hypeScore: 98,
    description: 'The classic Chicago colorway returns with a vintage reimagined look.',
    isRaffle: true,
    resalePrice: 450,
    preorderAvailable: false,
    raffles: [
      { id: 'r1', store: 'SNKRS App', url: 'https://nike.com', closesAt: new Date(Date.now() + 86400000).toISOString(), status: 'open', type: 'In-App' },
      { id: 'r2', store: 'END. Clothing', url: 'https://endclothing.com', closesAt: new Date(Date.now() + 43200000).toISOString(), status: 'open', type: 'Online' },
      { id: 'r3', store: 'KITH', url: 'https://kith.com', closesAt: new Date(Date.now() - 10000).toISOString(), status: 'closed', type: 'In-App' }
    ]
  },
  {
    id: '2',
    name: 'Nike Dunk Low "Panda"',
    brand: 'Nike',
    price: 110,
    image: 'https://picsum.photos/seed/dunk/800/800',
    dropDate: new Date(Date.now() - 86400000).toISOString(),
    hypeScore: 85,
    description: 'The ubiquitous black and white colorway that goes with everything.',
    isRaffle: false,
    resalePrice: 160,
    preorderAvailable: false,
  },
  {
    id: '3',
    name: 'Adidas Yeezy Boost 350 V2 "Bone"',
    brand: 'Adidas',
    price: 230,
    image: 'https://picsum.photos/seed/yeezy/800/800',
    dropDate: new Date(Date.now() + 86400000 * 5).toISOString(),
    hypeScore: 92,
    description: 'Clean triple white Primeknit upper with a translucent side stripe.',
    isRaffle: true,
    resalePrice: 320,
    preorderAvailable: true,
    raffles: [
       { id: 'r4', store: 'Adidas Confirmed', url: 'https://adidas.com', closesAt: new Date(Date.now() + 172800000).toISOString(), status: 'open', type: 'In-App' }
    ]
  },
  {
    id: '4',
    name: 'Travis Scott x Air Jordan 1 Low "Olive"',
    brand: 'Jordan',
    price: 150,
    image: 'https://picsum.photos/seed/travis/800/800',
    dropDate: new Date(Date.now() + 86400000 * 10).toISOString(),
    hypeScore: 100,
    description: 'La Flame returns with an olive suede construction and reverse swoosh.',
    isRaffle: true,
    resalePrice: 1200,
    preorderAvailable: true,
    raffles: [
      { id: 'r5', store: 'Travis Scott', url: 'https://travisscott.com', closesAt: new Date(Date.now() + 864000000).toISOString(), status: 'coming_soon', type: 'Online' }
    ]
  },
  {
    id: '5',
    name: 'New Balance 990v6 "Grey"',
    brand: 'New Balance',
    price: 200,
    image: 'https://picsum.photos/seed/nb/800/800',
    dropDate: new Date(Date.now() + 86400000).toISOString(),
    hypeScore: 75,
    description: 'The latest evolution of the dad shoe staple, featuring FuelCell foam.',
    isRaffle: false,
    resalePrice: 220,
    preorderAvailable: false,
  },
  // NEW RELEASES 2025-2026 (JORDAN)
  {
    id: '10',
    name: 'Air Jordan 1 High OG "Sail / Elephant Print"',
    brand: 'Jordan',
    price: 180,
    image: 'https://picsum.photos/seed/aj1sail/800/800',
    dropDate: new Date('2025-12-01').toISOString(),
    hypeScore: 88,
    description: 'Featuring the iconic elephant print on a sail base. SKU: IH4363-100',
    isRaffle: true,
    resalePrice: 240,
    preorderAvailable: true,
  },
  {
    id: '11',
    name: 'Air Jordan 11 "China"',
    brand: 'Jordan',
    price: 230,
    image: 'https://picsum.photos/seed/aj11china/800/800',
    dropDate: new Date('2025-12-01').toISOString(),
    hypeScore: 92,
    description: 'Exclusive regional release celebrating Chinese heritage. SKU: IM8352-670',
    isRaffle: true,
    resalePrice: 350,
    preorderAvailable: false,
  },
  {
    id: '12',
    name: 'Air Jordan 40 "Bordeaux"',
    brand: 'Jordan',
    price: 200,
    image: 'https://picsum.photos/seed/aj40bordeaux/800/800',
    dropDate: new Date('2025-12-01').toISOString(),
    hypeScore: 75,
    description: 'The latest performance flagship in a classic colorway. SKU: HM9931-601',
    isRaffle: false,
    resalePrice: 200,
    preorderAvailable: true,
  },
  {
    id: '13',
    name: 'PSG x Air Jordan 5',
    brand: 'Jordan',
    price: 225,
    image: 'https://picsum.photos/seed/psgaj5/800/800',
    dropDate: new Date('2025-12-03').toISOString(),
    hypeScore: 95,
    description: 'Latest collaboration with Paris Saint-Germain. SKU: HQ3004-001',
    isRaffle: true,
    resalePrice: 380,
    preorderAvailable: false,
  },
  {
    id: '14',
    name: 'A Ma Maniére x Air Jordan 6 "Smokey Mauve"',
    brand: 'Jordan',
    price: 250,
    image: 'https://picsum.photos/seed/amm6/800/800',
    dropDate: new Date('2025-12-05').toISOString(),
    hypeScore: 98,
    description: 'Luxury materials meet the AJ6 silhouette. SKU: IF3103-200',
    isRaffle: true,
    resalePrice: 450,
    preorderAvailable: false,
  },
  {
    id: '15',
    name: 'SoleFly x Air Jordan 3 "Fruits of Our Labor"',
    brand: 'Jordan',
    price: 220,
    image: 'https://picsum.photos/seed/solefly3/800/800',
    dropDate: new Date('2025-12-05').toISOString(),
    hypeScore: 94,
    description: 'Miami-inspired colorway from SoleFly. SKU: IF4491-100',
    isRaffle: true,
    resalePrice: 400,
    preorderAvailable: false,
  },
  {
    id: '16',
    name: 'A Ma Maniére x Air Jordan 4 "Dark Mocha"',
    brand: 'Jordan',
    price: 225,
    image: 'https://picsum.photos/seed/amm4mocha/800/800',
    dropDate: new Date('2025-12-12').toISOString(),
    hypeScore: 100,
    description: 'Sophisticated take on the AJ4 with premium nubuck. SKU: IF3102-200',
    isRaffle: true,
    resalePrice: 550,
    preorderAvailable: false,
  },
  {
    id: '17',
    name: 'Air Jordan 11 "Gamma Blue"',
    brand: 'Jordan',
    price: 230,
    image: 'https://picsum.photos/seed/gamma11/800/800',
    dropDate: new Date('2025-12-13').toISOString(),
    hypeScore: 97,
    description: 'The return of the highly coveted Gamma Blue 11s. SKU: CT8012-047',
    isRaffle: true,
    resalePrice: 400,
    preorderAvailable: true,
  },
  {
    id: '18',
    name: 'Air Jordan 8 "Bugs Bunny"',
    brand: 'Jordan',
    price: 210,
    image: 'https://picsum.photos/seed/aj8bugs/800/800',
    dropDate: new Date('2025-12-20').toISOString(),
    hypeScore: 89,
    description: 'Classic Looney Tunes connected colorway. SKU: 305381-100',
    isRaffle: false,
    resalePrice: 260,
    preorderAvailable: true,
  },
  {
    id: '19',
    name: 'Air Jordan 5 "Wolf Grey"',
    brand: 'Jordan',
    price: 210,
    image: 'https://picsum.photos/seed/aj5wolf/800/800',
    dropDate: new Date('2026-01-10').toISOString(),
    hypeScore: 85,
    description: 'Versatile grey suede construction. SKU: DD0587-002',
    isRaffle: false,
    resalePrice: 250,
    preorderAvailable: true,
  },
  {
    id: '20',
    name: 'Air Jordan 4 "Flight Club"',
    brand: 'Jordan',
    price: 215,
    image: 'https://picsum.photos/seed/aj4flight/800/800',
    dropDate: new Date('2026-01-17').toISOString(),
    hypeScore: 91,
    description: 'New colorway celebrating the legacy of flight. SKU: IM4002-100',
    isRaffle: true,
    resalePrice: 320,
    preorderAvailable: true,
  },
  {
    id: '21',
    name: 'Air Jordan 9 "Flint Grey"',
    brand: 'Jordan',
    price: 200,
    image: 'https://picsum.photos/seed/aj9flint/800/800',
    dropDate: new Date('2026-01-24').toISOString(),
    hypeScore: 80,
    description: 'Clean execution of the AJ9 silhouette. SKU: HV4794-100',
    isRaffle: false,
    resalePrice: 220,
    preorderAvailable: true,
  },
  {
    id: '22',
    name: 'Air Jordan 6 "Reverse Infrared"',
    brand: 'Jordan',
    price: 210,
    image: 'https://picsum.photos/seed/aj6infrared/800/800',
    dropDate: new Date('2026-02-14').toISOString(),
    hypeScore: 93,
    description: 'A flip on the iconic OG colorway. SKU: CT8529-001',
    isRaffle: true,
    resalePrice: 300,
    preorderAvailable: true,
  },
  {
    id: '23',
    name: 'Air Jordan 13 "Chicago"',
    brand: 'Jordan',
    price: 210,
    image: 'https://picsum.photos/seed/aj13chi/800/800',
    dropDate: new Date('2026-03-13').toISOString(),
    hypeScore: 90,
    description: 'OG Bulls colorway returns. SKU: 414571-102',
    isRaffle: true,
    resalePrice: 300,
    preorderAvailable: true,
  },
  {
    id: '24',
    name: 'Air Jordan 14 "Black / University Blue"',
    brand: 'Jordan',
    price: 210,
    image: 'https://picsum.photos/seed/aj14unc/800/800',
    dropDate: new Date('2026-03-21').toISOString(),
    hypeScore: 84,
    description: 'Stealthy black with UNC blue accents. SKU: 487471-002',
    isRaffle: false,
    resalePrice: 240,
    preorderAvailable: true,
  },
  // NIKE RELEASES
  {
    id: '25',
    name: 'Nike Air Force 1 Low "Lenticular"',
    brand: 'Nike',
    price: 140,
    image: 'https://picsum.photos/seed/af1lentic/800/800',
    dropDate: new Date('2025-12-01').toISOString(),
    hypeScore: 78,
    description: 'Classic AF1 silhouette featuring color-shifting lenticular materials.',
    isRaffle: false,
    resalePrice: 160,
    preorderAvailable: true,
  },
  {
    id: '26',
    name: 'Nike A’One "Dog Mom"',
    brand: 'Nike',
    price: 120,
    image: 'https://picsum.photos/seed/aone/800/800',
    dropDate: new Date('2025-12-01').toISOString(),
    hypeScore: 65,
    description: 'Women’s exclusive release celebrating pet culture with unique furry textures.',
    isRaffle: false,
    resalePrice: 140,
    preorderAvailable: true,
  },
  {
    id: '27',
    name: 'Nike SB Dunk Low Pro Premium "Dark Smoke Grey"',
    brand: 'Nike',
    price: 130,
    image: 'https://picsum.photos/seed/sbdarksmoke/800/800',
    dropDate: new Date('2025-12-02').toISOString(),
    hypeScore: 92,
    description: 'Premium materials in a stealthy Dark Smoke Grey and Black colorway.',
    isRaffle: true,
    resalePrice: 280,
    preorderAvailable: false,
  },
  {
    id: '28',
    name: 'Nike Blazer Low x Book "College Navy"',
    brand: 'Nike',
    price: 100,
    image: 'https://picsum.photos/seed/blazernavy/800/800',
    dropDate: new Date('2025-12-02').toISOString(),
    hypeScore: 80,
    description: 'Devin Booker collaboration in College Navy and Dark Obsidian.',
    isRaffle: true,
    resalePrice: 150,
    preorderAvailable: false,
  },
  {
    id: '29',
    name: 'Nike Blazer Low x Book "Campfire Orange"',
    brand: 'Nike',
    price: 100,
    image: 'https://picsum.photos/seed/blazerorange/800/800',
    dropDate: new Date('2025-12-02').toISOString(),
    hypeScore: 80,
    description: 'Devin Booker collaboration featuring warm Campfire Orange tones.',
    isRaffle: true,
    resalePrice: 150,
    preorderAvailable: false,
  },
  {
    id: '30',
    name: 'Nike Astrograbber "Sail / Light Silver"',
    brand: 'Nike',
    price: 110,
    image: 'https://picsum.photos/seed/astrograbber/800/800',
    dropDate: new Date('2025-12-02').toISOString(),
    hypeScore: 70,
    description: 'Retro-inspired silhouette in a clean Sail and Light Silver palette.',
    isRaffle: false,
    resalePrice: 120,
    preorderAvailable: true,
  },
  {
    id: '31',
    name: 'Nike Kobe 9 Elite Low Protro "Neo Turquoise"',
    brand: 'Nike',
    price: 210,
    image: 'https://picsum.photos/seed/kobe9neo/800/800',
    dropDate: new Date('2025-12-03').toISOString(),
    hypeScore: 96,
    description: 'The return of the high-top Flyknit masterpiece in Neo Turquoise and Volt.',
    isRaffle: true,
    resalePrice: 400,
    preorderAvailable: false,
  },
  {
    id: '32',
    name: 'Nike Air Max Goadome "Black Pony Hair"',
    brand: 'Nike',
    price: 190,
    image: 'https://picsum.photos/seed/goadome/800/800',
    dropDate: new Date('2025-12-11').toISOString(),
    hypeScore: 75,
    description: 'Rugged boot silhouette updated with premium Black Pony Hair textures.',
    isRaffle: false,
    resalePrice: 220,
    preorderAvailable: true,
  },
  {
    id: '33',
    name: 'Palace x Nike Air Max DN8',
    brand: 'Nike',
    price: 180,
    image: 'https://picsum.photos/seed/palacedn8/800/800',
    dropDate: new Date('2025-12-17').toISOString(),
    hypeScore: 98,
    description: 'Palace Skateboards takes on the futuristic Air Max DN8.',
    isRaffle: true,
    resalePrice: 350,
    preorderAvailable: false,
  },
  {
    id: '34',
    name: 'Nike Kobe 1 Protro "81 Points"',
    brand: 'Nike',
    price: 190,
    image: 'https://picsum.photos/seed/kobe181/800/800',
    dropDate: new Date('2026-01-22').toISOString(),
    hypeScore: 100,
    description: 'Celebrating the 20th anniversary of Kobe’s legendary 81-point game.',
    isRaffle: true,
    resalePrice: 600,
    preorderAvailable: false,
  },
  {
    id: '35',
    name: 'Nike KD 6 "PBJ"',
    brand: 'Nike',
    price: 160,
    image: 'https://picsum.photos/seed/kd6pbj/800/800',
    dropDate: new Date('2026-01-23').toISOString(),
    hypeScore: 88,
    description: 'The fan-favorite Peanut Butter & Jelly colorway returns on the KD 6.',
    isRaffle: true,
    resalePrice: 240,
    preorderAvailable: true,
  },
  {
    id: '36',
    name: 'Nike Kobe 8 Protro "Year of the Horse"',
    brand: 'Nike',
    price: 190,
    image: 'https://picsum.photos/seed/kobe8yoth/800/800',
    dropDate: new Date('2026-01-31').toISOString(),
    hypeScore: 97,
    description: 'Lunar New Year edition featuring special YOTH details.',
    isRaffle: true,
    resalePrice: 450,
    preorderAvailable: false,
  },
  {
    id: '37',
    name: 'Nike Book 2 "Spiridon"',
    brand: 'Nike',
    price: 150,
    image: 'https://picsum.photos/seed/book2spiridon/800/800',
    dropDate: new Date('2026-02-06').toISOString(),
    hypeScore: 85,
    description: 'Devin Booker’s second signature shoe inspired by the classic Spiridon.',
    isRaffle: true,
    resalePrice: 200,
    preorderAvailable: true,
  },
  {
    id: '38',
    name: 'Nike Air Diamond Turf 2 "Fire Red"',
    brand: 'Nike',
    price: 160,
    image: 'https://picsum.photos/seed/dt2fire/800/800',
    dropDate: new Date('2026-02-07').toISOString(),
    hypeScore: 82,
    description: 'Deion Sanders’ iconic turf trainer returns in Fire Red.',
    isRaffle: false,
    resalePrice: 180,
    preorderAvailable: true,
  },
  {
    id: '39',
    name: 'Nike Ja 3 LX "Cobalt Bliss"',
    brand: 'Nike',
    price: 140,
    image: 'https://picsum.photos/seed/ja3cobalt/800/800',
    dropDate: new Date('2026-02-13').toISOString(),
    hypeScore: 84,
    description: 'Luxury edition of Ja Morant’s third signature shoe.',
    isRaffle: false,
    resalePrice: 160,
    preorderAvailable: true,
  },
  {
    id: '40',
    name: 'Nike Air Foamposite Pro "University Blue"',
    brand: 'Nike',
    price: 240,
    image: 'https://picsum.photos/seed/foampblue/800/800',
    dropDate: new Date('2026-02-13').toISOString(),
    hypeScore: 91,
    description: 'The cult classic Foamposite Pro in a stunning University Blue shell.',
    isRaffle: true,
    resalePrice: 320,
    preorderAvailable: true,
  },
  {
    id: '41',
    name: 'Nike Air Zoom Huarache 2K4',
    brand: 'Nike',
    price: 160,
    image: 'https://picsum.photos/seed/huarache2k4/800/800',
    dropDate: new Date('2026-05-01').toISOString(),
    hypeScore: 78,
    description: 'One of the greatest basketball performance shoes of all time returns.',
    isRaffle: false,
    resalePrice: 180,
    preorderAvailable: true,
  },
  {
    id: '42',
    name: 'Nike KD 19 "Bright Ceramic"',
    brand: 'Nike',
    price: 170,
    image: 'https://picsum.photos/seed/kd19ceramic/800/800',
    dropDate: new Date('2026-05-29').toISOString(),
    hypeScore: 85,
    description: 'Kevin Durant’s 19th signature model in a vibrant colorway.',
    isRaffle: false,
    resalePrice: 190,
    preorderAvailable: true,
  },
  // ADIDAS RELEASES (EARLY 2026)
  {
    id: '43',
    name: 'Adidas Crazy 3 "White Black"',
    brand: 'Adidas',
    price: 140,
    image: 'https://picsum.photos/seed/crazy3wb/800/800',
    dropDate: new Date('2026-02-01').toISOString(),
    hypeScore: 82,
    description: 'A retro of the classic KB8 III basketball shoe.',
    isRaffle: false,
    resalePrice: 160,
    preorderAvailable: true,
  },
  {
    id: '44',
    name: 'Adidas Crazy 3 "Silver Metallic"',
    brand: 'Adidas',
    price: 140,
    image: 'https://picsum.photos/seed/crazy3silver/800/800',
    dropDate: new Date('2026-05-01').toISOString(),
    hypeScore: 84,
    description: 'Futuristic Silver Metallic colorway of the Crazy 3 retro.',
    isRaffle: false,
    resalePrice: 170,
    preorderAvailable: true,
  },
  {
    id: '45',
    name: 'Adidas Anthony Edwards 2 "Lucid Pink"',
    brand: 'Adidas',
    price: 130,
    image: 'https://picsum.photos/seed/ae2pink/800/800',
    dropDate: new Date('2026-01-17').toISOString(),
    hypeScore: 94,
    description: 'The next chapter in Anthony Edwards signature line in Lucid Pink.',
    isRaffle: true,
    resalePrice: 220,
    preorderAvailable: true,
  },
  {
    id: '46',
    name: 'Adidas Anthony Edwards 2 "Lime Burst"',
    brand: 'Adidas',
    price: 130,
    image: 'https://picsum.photos/seed/ae2lime/800/800',
    dropDate: new Date('2026-04-12').toISOString(),
    hypeScore: 93,
    description: 'Vibrant Lime Burst colorway of the AE 2.',
    isRaffle: true,
    resalePrice: 200,
    preorderAvailable: true,
  },
  {
    id: '47',
    name: 'Adidas Anthony Edwards 2 "Glow"',
    brand: 'Adidas',
    price: 130,
    image: 'https://picsum.photos/seed/ae2glow/800/800',
    dropDate: new Date('2026-04-12').toISOString(),
    hypeScore: 95,
    description: 'Glow-in-the-dark edition of the Anthony Edwards 2.',
    isRaffle: true,
    resalePrice: 250,
    preorderAvailable: true,
  },
  {
    id: '48',
    name: 'BAPE x Adidas World Cup Pack 2026',
    brand: 'Adidas',
    price: 180,
    image: 'https://picsum.photos/seed/bapeadidas/800/800',
    dropDate: new Date('2026-02-15').toISOString(),
    hypeScore: 97,
    description: 'Collab pack featuring Samba, Campus 00s, and adistar HRMY.',
    isRaffle: true,
    resalePrice: 350,
    preorderAvailable: false,
  },
  // NEW BALANCE RELEASES (DEC 2025)
  {
    id: '49',
    name: 'New Balance 740',
    brand: 'New Balance',
    price: 110,
    image: 'https://picsum.photos/seed/nb740/800/800',
    dropDate: new Date('2025-12-01').toISOString(),
    hypeScore: 72,
    description: 'The return of the reliable 740 silhouette in a fresh colorway.',
    isRaffle: false,
    resalePrice: 120,
    preorderAvailable: true,
  },
  {
    id: '50',
    name: 'New Balance 204L',
    brand: 'New Balance',
    price: 100,
    image: 'https://picsum.photos/seed/nb204l/800/800',
    dropDate: new Date('2025-12-02').toISOString(),
    hypeScore: 68,
    description: 'Modern lifestyle runner focusing on lightweight comfort.',
    isRaffle: false,
    resalePrice: 110,
    preorderAvailable: true,
  },
  {
    id: '51',
    name: 'New Balance 1906L "Loafer"',
    brand: 'New Balance',
    price: 160,
    image: 'https://picsum.photos/seed/nb1906l/800/800',
    dropDate: new Date('2025-12-03').toISOString(),
    hypeScore: 94,
    description: 'The controversial yet highly anticipated loafer adaptation of the 1906R tech runner.',
    isRaffle: true,
    resalePrice: 250,
    preorderAvailable: false,
  },
  {
    id: '52',
    name: 'NB Numeric Tom Knox 600',
    brand: 'New Balance',
    price: 95,
    image: 'https://picsum.photos/seed/nbknox600/800/800',
    dropDate: new Date('2025-12-08').toISOString(),
    hypeScore: 75,
    description: 'Tom Knox signature skate shoe featuring reinforced durability and board feel.',
    isRaffle: false,
    resalePrice: 110,
    preorderAvailable: true,
  },
  {
    id: '53',
    name: 'New Balance ABZORB 2000',
    brand: 'New Balance',
    price: 150,
    image: 'https://picsum.photos/seed/nbabzorb2000/800/800',
    dropDate: new Date('2025-12-10').toISOString(),
    hypeScore: 88,
    description: 'Y2K era aesthetics meet modern comfort in the ABZORB 2000 revival.',
    isRaffle: false,
    resalePrice: 180,
    preorderAvailable: true,
  },
  // PUMA RELEASES
  {
    id: '54',
    name: 'PUMA Speedcat Wedge',
    brand: 'PUMA',
    price: 110,
    image: 'https://picsum.photos/seed/speedcatwedge/800/800',
    dropDate: new Date('2025-12-04').toISOString(),
    hypeScore: 76,
    description: 'Elevated motorsport-inspired silhouette with a wedge heel.',
    isRaffle: false,
    resalePrice: 130,
    preorderAvailable: true,
  },
  {
    id: '55',
    name: 'PUMA Speedcat Ballet Lux',
    brand: 'PUMA',
    price: 100,
    image: 'https://picsum.photos/seed/speedcatballet/800/800',
    dropDate: new Date('2025-12-04').toISOString(),
    hypeScore: 85,
    description: 'Ballet flat hybrid blending coquette aesthetics with racing DNA.',
    isRaffle: false,
    resalePrice: 140,
    preorderAvailable: true,
  },
  {
    id: '56',
    name: 'PUMA Speedcat Lux',
    brand: 'PUMA',
    price: 120,
    image: 'https://picsum.photos/seed/speedcatluxw/800/800',
    dropDate: new Date('2025-12-04').toISOString(),
    hypeScore: 82,
    description: 'Premium leather execution of the classic Speedcat icon.',
    isRaffle: false,
    resalePrice: 150,
    preorderAvailable: true,
  },
  {
    id: '57',
    name: 'PUMA Speedcat Lux (Unisex)',
    brand: 'PUMA',
    price: 120,
    image: 'https://picsum.photos/seed/speedcatluxu/800/800',
    dropDate: new Date('2025-12-04').toISOString(),
    hypeScore: 80,
    description: 'Unisex premium version of the motorsport staple.',
    isRaffle: false,
    resalePrice: 140,
    preorderAvailable: true,
  },
  {
    id: '58',
    name: 'PUMA LaFrancé RNR',
    brand: 'PUMA',
    price: 110,
    image: 'https://picsum.photos/seed/lafrance/800/800',
    dropDate: new Date('2025-12-05').toISOString(),
    hypeScore: 88,
    description: 'Bold lifestyle silhouette from LaMelo Ball’s LaFrancé line.',
    isRaffle: false,
    resalePrice: 150,
    preorderAvailable: true,
  },
  {
    id: '59',
    name: 'PUMA MB.05 Metallic',
    brand: 'PUMA',
    price: 140,
    image: 'https://picsum.photos/seed/mb05metallic/800/800',
    dropDate: new Date('2025-12-12').toISOString(),
    hypeScore: 94,
    description: 'LaMelo Ball’s fifth signature shoe in a flashy Metallic finish.',
    isRaffle: true,
    resalePrice: 200,
    preorderAvailable: false,
  },
  {
    id: '60',
    name: 'PUMA All-Pro NITRO™ 2 E.T.',
    brand: 'PUMA',
    price: 140,
    image: 'https://picsum.photos/seed/allproet/800/800',
    dropDate: new Date('2025-12-19').toISOString(),
    hypeScore: 89,
    description: 'Performance basketball shoe with E.T. extraterrestrial details.',
    isRaffle: true,
    resalePrice: 180,
    preorderAvailable: false,
  },
  {
    id: '61',
    name: 'PUMA Suede E.T. (Collection)',
    brand: 'PUMA',
    price: 90,
    image: 'https://picsum.photos/seed/suedeet/800/800',
    dropDate: new Date('2025-12-19').toISOString(),
    hypeScore: 91,
    description: 'Classic Suede silhouette celebrating the E.T. collaboration.',
    isRaffle: true,
    resalePrice: 150,
    preorderAvailable: true,
  },
  {
    id: '62',
    name: 'PUMA Speedcat Ballet Doelette',
    brand: 'PUMA',
    price: 100,
    image: 'https://picsum.photos/seed/doelette/800/800',
    dropDate: new Date('2026-01-09').toISOString(),
    hypeScore: 86,
    description: 'Soft, coquette-inspired take on the trending ballet sneaker.',
    isRaffle: false,
    resalePrice: 140,
    preorderAvailable: true,
  }
];

export const MOCK_POSTS: Post[] = [
  {
    id: '101',
    username: 'HypeBeast99',
    userAvatar: 'https://picsum.photos/seed/user1/100/100',
    content: 'Just secured the W on the Lost & Founds! 🔥 The quality on these is actually insane in hand.',
    image: 'https://picsum.photos/seed/win/600/400',
    likes: 420,
    isLiked: false,
    comments: [
      { id: 'c1', username: 'Kicks4Life', avatar: 'https://picsum.photos/seed/u3/50/50', text: 'Huge W bro!', timestamp: new Date().toISOString() }
    ],
    timestamp: new Date().toISOString(),
  },
  {
    id: '102',
    username: 'SneakerHead_Sarah',
    userAvatar: 'https://picsum.photos/seed/user2/100/100',
    content: 'Unpopular opinion: Dunks are overrated. New Balance is the wave right now. Comfort > Hype.',
    likes: 89,
    isLiked: true,
    comments: [],
    timestamp: new Date(Date.now() - 3600000).toISOString(),
  },
];

export const getRarityConfig = (score: number) => {
  if (score >= 90) return { label: 'GRAIL', color: 'bg-amber-500 text-black', border: 'border-amber-500', text: 'text-amber-400' };
  if (score >= 80) return { label: 'HYPE', color: 'bg-fuchsia-500 text-white', border: 'border-fuchsia-500', text: 'text-fuchsia-400' };
  if (score >= 60) return { label: 'LIMITED', color: 'bg-blue-500 text-white', border: 'border-blue-500', text: 'text-blue-400' };
  return { label: 'COMMON', color: 'bg-zinc-600 text-zinc-100', border: 'border-zinc-600', text: 'text-zinc-400' };
};