import { Sneaker, Post, Badge, LeaderboardUser, Conversation, Story, Retailer } from './types';

export const APP_VERSION = '1.2.7 (Extended 2026 Adidas)';

export const NEWS_TICKER = [
  "BREAKING: Adidas Harden Vol. 10 'Hi-Res Yellow' confirmed for May 2026",
  "MARKET UPDATE: Patent Leather Sambas projected to be the top 2026 trend",
  "LEAK: Nike Kobe 10 Protro 'Halo' materials list updated",
  "REMINDER: SNKRS Draw for Dunk Low 'Panda' opens in 1 hour",
  "INDUSTRY: Jordan Brand market share hits record high in 2025"
];

export const BADGES: Badge[] = [
  { id: '1', icon: '👑', label: 'OG Member', description: 'Joined during Beta', color: 'bg-amber-500/20 text-amber-500 border-amber-500' },
  { id: '2', icon: '💎', label: 'Diamond Hands', description: 'Portfolio value > $1k', color: 'bg-cyan-500/20 text-cyan-500 border-cyan-500' },
  { id: '3', icon: '🔥', label: 'Hypebeast', description: 'Copped 5+ Hype items', color: 'bg-red-500/20 text-red-500 border-red-500' },
  { id: '4', icon: '🤖', label: 'Bot Slayer', description: 'Beat the bots manually', color: 'bg-violet-500/20 text-violet-500 border-violet-500' },
];

export const MOCK_LEADERBOARD: LeaderboardUser[] = [
  { rank: 1, username: 'KicksKing_99', avatar: 'https://ui-avatars.com/api/?name=Kicks+King&background=F59E0B&color=fff', portfolioValue: 45200, change: 12.5 },
  { rank: 2, username: 'SoleSurvivor', avatar: 'https://ui-avatars.com/api/?name=Sole+Survivor&background=10B981&color=fff', portfolioValue: 38900, change: 8.2 },
  { rank: 3, username: 'HypeBeast_X', avatar: 'https://ui-avatars.com/api/?name=Hype+Beast&background=8B5CF6&color=fff', portfolioValue: 29500, change: -2.1 },
];

export const MOCK_NOTIFICATIONS = [
  { id: '1', title: 'Shock Drop Alert', message: 'Jordan 1 Low Banned just shock dropped on SNKRS!', time: '2m ago', read: false },
  { id: '2', title: 'Price Change', message: 'Jordan 1 Lost & Found resale dropped by $20.', time: '1h ago', read: false },
  { id: '3', title: 'Restock', message: 'Nike Dunk Low Panda restocked at Foot Locker.', time: '3h ago', read: true },
];

export const MOCK_STORIES: Story[] = [
  { id: 's1', user: 'SneakPeak', avatar: 'https://cdn-icons-png.flaticon.com/512/2589/2589903.png', image: 'https://picsum.photos/seed/s1/400/800', title: 'Weekly Recap', viewed: false },
  { id: 's2', user: 'Nike', avatar: 'https://ui-avatars.com/api/?name=Nike&background=000&color=fff', image: 'https://picsum.photos/seed/s2/400/800', title: 'SNKRS Day', viewed: false },
  { id: 's3', user: 'Kith', avatar: 'https://ui-avatars.com/api/?name=Kith&background=fff&color=000', image: 'https://picsum.photos/seed/s3/400/800', title: 'New Lookbook', viewed: true },
  { id: 's4', user: 'Yeezy', avatar: 'https://ui-avatars.com/api/?name=Yeezy&background=555&color=fff', image: 'https://picsum.photos/seed/s4/400/800', title: 'Archive Drop', viewed: false },
];

export const MOCK_CONVERSATIONS: Conversation[] = [
  {
    id: 'c1',
    withUser: 'J23_Official',
    userAvatar: 'https://ui-avatars.com/api/?name=J+23&background=ef4444&color=fff',
    lastMessage: 'Would you take $350 for the Lost & Founds?',
    unread: 2,
    messages: [
      { id: 'm1', sender: 'other', text: 'Yo, nice collection.', timestamp: '10:00 AM', type: 'text' },
      { id: 'm2', sender: 'me', text: 'Thanks bro! Trying to build it up.', timestamp: '10:05 AM', type: 'text' },
      { id: 'm3', sender: 'other', text: 'Would you take $350 for the Lost & Founds?', timestamp: '10:15 AM', type: 'text' }
    ]
  },
  {
    id: 'c2',
    withUser: 'ResellGod',
    userAvatar: 'https://ui-avatars.com/api/?name=Resell+God&background=10b981&color=fff',
    lastMessage: 'Trade Offer Sent',
    unread: 0,
    messages: [
      { id: 'm1', sender: 'me', text: 'Still have the Travis Scotts?', timestamp: 'Yesterday', type: 'text' },
      { id: 'm2', sender: 'other', text: 'Yeah but only looking for trades.', timestamp: 'Yesterday', type: 'text' }
    ]
  }
];

export const DEFAULT_RETAILERS: Retailer[] = [
  { id: 'sx', name: 'StockX', baseUrl: 'https://stockx.com/search?s=', affiliateParam: '&utm_source=SneakPeak', color: 'text-green-500', bg: 'bg-green-900/20', abbr: 'SX' },
  { id: 'gt', name: 'GOAT', baseUrl: 'https://www.goat.com/search?query=', affiliateParam: '', color: 'text-blue-500', bg: 'bg-blue-900/20', abbr: 'GO' },
  { id: 'eb', name: 'eBay Sneakers', baseUrl: 'https://www.ebay.com/sch/i.html?_nkw=', affiliateParam: '', color: 'text-yellow-500', bg: 'bg-yellow-900/20', abbr: 'EB' },
  { id: 'fl', name: 'Foot Locker', baseUrl: 'https://www.footlocker.com/search?query=', affiliateParam: '', color: 'text-red-500', bg: 'bg-red-900/20', abbr: 'FL' },
];

export const MOCK_SNEAKERS: Sneaker[] = [
  {
    id: '1',
    name: 'Air Jordan 1 High OG "Lost & Found"',
    brand: 'Jordan',
    price: 180,
    image: 'https://picsum.photos/seed/jordan1/800/800',
    dropDate: new Date(Date.now() + 86400000 * 2).toISOString(),
    hypeScore: 98,
    description: 'The classic Chicago colorway returns with a vintage reimagined look.',
    isRaffle: true,
    resalePrice: 450,
    preorderAvailable: false,
    raffles: [
      { id: 'r1', store: 'SNKRS App', url: 'https://nike.com', closesAt: new Date(Date.now() + 86400000).toISOString(), status: 'open', type: 'In-App' },
      { id: 'r2', store: 'END. Clothing', url: 'https://endclothing.com', closesAt: new Date(Date.now() + 43200000).toISOString(), status: 'open', type: 'Online' },
      { id: 'r3', store: 'KITH', url: 'https://kith.com', closesAt: new Date(Date.now() - 10000).toISOString(), status: 'closed', type: 'In-App' }
    ]
  },
  {
    id: '2',
    name: 'Nike Dunk Low "Panda"',
    brand: 'Nike',
    price: 110,
    image: 'https://picsum.photos/seed/dunk/800/800',
    dropDate: new Date(Date.now() - 86400000).toISOString(),
    hypeScore: 85,
    description: 'The ubiquitous black and white colorway that goes with everything.',
    isRaffle: false,
    resalePrice: 160,
    preorderAvailable: false,
  },
  // 2026 NIKE RELEASES
  {
    id: 'n2026-1',
    name: 'Nike A’One GS “Gold Grillz”',
    brand: 'Nike',
    price: 105,
    image: 'https://picsum.photos/seed/aonegold/800/800',
    dropDate: '2026-01-01T00:00:00.000Z',
    hypeScore: 78,
    description: 'A flashy Grade School exclusive featuring metallic gold detailing and premium textures.',
    isRaffle: false,
    resalePrice: 150,
    preorderAvailable: true,
  },
  {
    id: 'n2026-2',
    name: 'Nike A’One “Stone Mauve”',
    brand: 'Nike',
    price: 120,
    image: 'https://picsum.photos/seed/aonemauve/800/800',
    dropDate: '2026-01-01T00:00:00.000Z',
    hypeScore: 72,
    description: 'Earthy mauve tones meet the modern A\'One silhouette for a sophisticated look.',
    isRaffle: false,
    resalePrice: 140,
    preorderAvailable: true,
  },
  {
    id: 'n2026-3',
    name: 'Nike Air Zoom Huarache 2K4',
    brand: 'Nike',
    price: 160,
    image: 'https://picsum.photos/seed/huarache2k4/800/800',
    dropDate: '2026-05-01T00:00:00.000Z',
    hypeScore: 89,
    description: 'One of the greatest performance basketball silhouettes of all time returns in its classic form.',
    isRaffle: true,
    resalePrice: 220,
    preorderAvailable: true,
  },
  {
    id: 'n2026-4',
    name: 'Nike Shox BB4 “Olympic”',
    brand: 'Nike',
    price: 170,
    image: 'https://picsum.photos/seed/shoxbb4/800/800',
    dropDate: '2026-06-01T00:00:00.000Z',
    hypeScore: 84,
    description: 'The legendary Vince Carter silhouette returns in the iconic patriotic Olympic colorway.',
    isRaffle: true,
    resalePrice: 240,
    preorderAvailable: true,
  },
  {
    id: 'n2026-5',
    name: 'Nike KD 6 “Night Vision”',
    brand: 'Nike',
    price: 160,
    image: 'https://picsum.photos/seed/kd6night/800/800',
    dropDate: '2026-06-19T00:00:00.000Z',
    hypeScore: 92,
    description: 'Kevin Durant\'s sixth signature shoe returns with a stealthy, light-reflective glow.',
    isRaffle: true,
    resalePrice: 280,
    preorderAvailable: false,
  },
  {
    id: 'n2026-6',
    name: 'Nike Kobe 10 Elite Low Protro “Halo”',
    brand: 'Nike',
    price: 210,
    image: 'https://picsum.photos/seed/kobe10halo/800/800',
    dropDate: '2026-08-23T00:00:00.000Z',
    hypeScore: 100,
    description: 'Part of the prestigious Halo series, celebrating Kobe Bryant’s birthday with a triple white masterpiece.',
    isRaffle: true,
    resalePrice: 450,
    preorderAvailable: false,
  },
  // 2026 ADIDAS RELEASES
  {
    id: 'a2026-1',
    name: 'Adidas Harden Vol. 10 “Hi-Res Yellow”',
    brand: 'Adidas',
    price: 160,
    image: 'https://picsum.photos/seed/harden10yellow/800/800',
    dropDate: '2026-05-16T00:00:00.000Z',
    hypeScore: 86,
    description: 'James Harden’s tenth signature shoe debuts in a high-vis yellow performance mesh. Features next-gen energy return.',
    isRaffle: true,
    resalePrice: 220,
    preorderAvailable: true,
  },
  {
    id: 'a2026-2',
    name: 'Adidas Crazy 2 “USA”',
    brand: 'Adidas',
    price: 150,
    image: 'https://picsum.photos/seed/crazy2usa/800/800',
    dropDate: '2026-06-01T00:00:00.000Z',
    hypeScore: 81,
    description: 'The aggressive 90s silhouette returns in a patriotic Red, White, and Blue execution.',
    isRaffle: false,
    resalePrice: 190,
    preorderAvailable: true,
  },
  {
    id: 'a2026-3',
    name: 'Adidas Samba OG “Patent Leather”',
    brand: 'Adidas',
    price: 120,
    image: 'https://picsum.photos/seed/sambapatent/800/800',
    dropDate: '2026-02-15T00:00:00.000Z',
    hypeScore: 90,
    description: 'Tapping into the 2026 trend cycle, the Samba returns in premium high-gloss patent leather.',
    isRaffle: false,
    resalePrice: 180,
    preorderAvailable: true,
  },
  // START OF 2026 JORDAN DROPS
  {
    id: 'j2026-1',
    name: 'Air Jordan 4 WMNS "Valentine’s Day"',
    brand: 'Jordan',
    price: 215,
    image: 'https://picsum.photos/seed/aj4valentine/800/800',
    dropDate: '2026-02-07T00:00:00.000Z',
    hypeScore: 94,
    description: 'A romantic take on the AJ4 featuring premium pink and red tones. Women’s exclusive.',
    isRaffle: true,
    resalePrice: 320,
    preorderAvailable: true,
  },
  {
    id: 'j2026-2',
    name: 'Air Jordan 10 WMNS "Hydrangeas"',
    brand: 'Jordan',
    price: 200,
    image: 'https://picsum.photos/seed/aj10hydrangea/800/800',
    dropDate: '2026-02-12T00:00:00.000Z',
    hypeScore: 82,
    description: 'Soft floral-inspired tones bring a fresh look to the iconic AJ10 silhouette.',
    isRaffle: false,
    resalePrice: 240,
    preorderAvailable: true,
  },
  {
    id: 'j2026-3',
    name: 'Air Jordan 1 High OG "All-Star"',
    brand: 'Jordan',
    price: 180,
    image: 'https://picsum.photos/seed/aj1allstar26/800/800',
    dropDate: '2026-02-13T00:00:00.000Z',
    hypeScore: 96,
    description: 'Celebrating the All-Star weekend with a futuristic, material-heavy construction.',
    isRaffle: true,
    resalePrice: 350,
    preorderAvailable: false,
  },
  {
    id: '22',
    name: 'Air Jordan 6 "Reverse Infrared"',
    brand: 'Jordan',
    price: 210,
    image: 'https://picsum.photos/seed/aj6infrared/800/800',
    dropDate: '2026-02-14T00:00:00.000Z',
    hypeScore: 93,
    description: 'A flip on the iconic OG colorway with vibrant infrared panels.',
    isRaffle: true,
    resalePrice: 300,
    preorderAvailable: true,
  },
  {
    id: 'j2026-4',
    name: 'Air Jordan 1 Low OG "CNY"',
    brand: 'Jordan',
    price: 150,
    image: 'https://picsum.photos/seed/aj1lcny/800/800',
    dropDate: '2026-02-17T00:00:00.000Z',
    hypeScore: 91,
    description: 'Celebrating the Lunar New Year with intricate embroidery and premium materials.',
    isRaffle: true,
    resalePrice: 280,
    preorderAvailable: false,
  },
  {
    id: '19',
    name: 'Air Jordan 5 "Wolf Grey"',
    brand: 'Jordan',
    price: 210,
    image: 'https://picsum.photos/seed/aj5wolf/800/800',
    dropDate: '2026-02-28T00:00:00.000Z',
    hypeScore: 89,
    description: 'The return of the versatile Wolf Grey colorway on the AJ5 silhouette.',
    isRaffle: false,
    resalePrice: 260,
    preorderAvailable: true,
  },
  {
    id: 'j2026-5',
    name: 'Air Jordan 11 Low "University Blue"',
    brand: 'Jordan',
    price: 190,
    image: 'https://picsum.photos/seed/aj11lunc/800/800',
    dropDate: '2026-04-18T00:00:00.000Z',
    hypeScore: 95,
    description: 'Clean UNC blue patent leather meets a crisp white mesh upper for the spring.',
    isRaffle: true,
    resalePrice: 280,
    preorderAvailable: true,
  },
  {
    id: 'j2026-6',
    name: 'Air Jordan 4 "Toro Bravo"',
    brand: 'Jordan',
    price: 215,
    image: 'https://picsum.photos/seed/aj4toro/800/800',
    dropDate: '2026-05-02T00:00:00.000Z',
    hypeScore: 98,
    description: 'The fan-favorite all-red AJ4 returns to dominate the summer rotation.',
    isRaffle: true,
    resalePrice: 400,
    preorderAvailable: true,
  },
  {
    id: 'j2026-7',
    name: 'Air Jordan 1 Low OG "Banned"',
    brand: 'Jordan',
    price: 140,
    image: 'https://picsum.photos/seed/aj1lbanned/800/800',
    dropDate: '2026-05-16T00:00:00.000Z',
    hypeScore: 97,
    description: 'The legendary Bred colorway adapted for the classic OG low-top shape.',
    isRaffle: true,
    resalePrice: 250,
    preorderAvailable: false,
  },
  {
    id: 'j2026-8',
    name: 'Air Jordan 12 "Bloodline"',
    brand: 'Jordan',
    price: 200,
    image: 'https://picsum.photos/seed/aj12bloodline/800/800',
    dropDate: '2026-05-23T00:00:00.000Z',
    hypeScore: 88,
    description: 'Striking black and red color-blocking that pays homage to MJ’s legacy.',
    isRaffle: false,
    resalePrice: 240,
    preorderAvailable: true,
  },
  {
    id: 'j2026-9',
    name: 'Air Jordan 13 "Flint"',
    brand: 'Jordan',
    price: 210,
    image: 'https://picsum.photos/seed/aj13flint26/800/800',
    dropDate: '2026-06-20T00:00:00.000Z',
    hypeScore: 92,
    description: 'The return of the classic blue reflective mesh and grey suede Flint 13s.',
    isRaffle: true,
    resalePrice: 280,
    preorderAvailable: true,
  },
  {
    id: 'j2026-10',
    name: 'Air Jordan 5 "Sunset"',
    brand: 'Jordan',
    price: 210,
    image: 'https://picsum.photos/seed/aj5sunset/800/800',
    dropDate: '2026-07-01T00:00:00.000Z',
    hypeScore: 86,
    description: 'Vibrant gradients and sunset-inspired hues on the AJ5 silhouette.',
    isRaffle: false,
    resalePrice: 250,
    preorderAvailable: true,
  },
  {
    id: 'j2026-11',
    name: 'Air Jordan 4 "Comic"',
    brand: 'Jordan',
    price: 215,
    image: 'https://picsum.photos/seed/aj4comic/800/800',
    dropDate: '2026-07-25T00:00:00.000Z',
    hypeScore: 99,
    description: 'A bold, hand-drawn aesthetic inspired by vintage comic book art.',
    isRaffle: true,
    resalePrice: 450,
    preorderAvailable: false,
  },
  // OTHER BRAND RELEASES
  {
    id: '3',
    name: 'Adidas Yeezy Boost 350 V2 "Bone"',
    brand: 'Adidas',
    price: 230,
    image: 'https://picsum.photos/seed/yeezy/800/800',
    dropDate: new Date(Date.now() + 86400000 * 5).toISOString(),
    hypeScore: 92,
    description: 'Clean triple white Primeknit upper with a translucent side stripe.',
    isRaffle: true,
    resalePrice: 320,
    preorderAvailable: true,
    raffles: [
       { id: 'r4', store: 'Adidas Confirmed', url: 'https://adidas.com', closesAt: new Date(Date.now() + 172800000).toISOString(), status: 'open', type: 'In-App' }
    ]
  },
  {
    id: '4',
    name: 'Travis Scott x Air Jordan 1 Low "Olive"',
    brand: 'Jordan',
    price: 150,
    image: 'https://picsum.photos/seed/travis/800/800',
    dropDate: new Date(Date.now() + 86400000 * 10).toISOString(),
    hypeScore: 100,
    description: 'La Flame returns with an olive suede construction and reverse swoosh.',
    isRaffle: true,
    resalePrice: 1200,
    preorderAvailable: true,
    raffles: [
      { id: 'r5', store: 'Travis Scott', url: 'https://travisscott.com', closesAt: new Date(Date.now() + 864000000).toISOString(), status: 'coming_soon', type: 'Online' }
    ]
  },
  {
    id: '5',
    name: 'New Balance 990v6 "Grey"',
    brand: 'New Balance',
    price: 200,
    image: 'https://picsum.photos/seed/nb/800/800',
    dropDate: new Date(Date.now() + 86400000).toISOString(),
    hypeScore: 75,
    description: 'The latest evolution of the dad shoe staple, featuring FuelCell foam.',
    isRaffle: false,
    resalePrice: 220,
    preorderAvailable: false,
  }
];

export const MOCK_POSTS: Post[] = [
  {
    id: '101',
    username: 'HypeBeast99',
    userAvatar: 'https://picsum.photos/seed/user1/100/100',
    content: 'Just secured the W on the Lost & Founds! 🔥 The quality on these is actually insane in hand.',
    image: 'https://picsum.photos/seed/win/600/400',
    likes: 420,
    isLiked: false,
    comments: [
      { id: 'c1', username: 'Kicks4Life', avatar: 'https://picsum.photos/seed/u3/50/50', text: 'Huge W bro!', timestamp: new Date().toISOString() }
    ],
    timestamp: new Date().toISOString(),
  },
  {
    id: '102',
    username: 'SneakerHead_Sarah',
    userAvatar: 'https://picsum.photos/seed/user2/100/100',
    content: 'Unpopular opinion: Dunks are overrated. New Balance is the wave right now. Comfort > Hype.',
    likes: 89,
    isLiked: true,
    comments: [],
    timestamp: new Date(Date.now() - 3600000).toISOString(),
  },
];

export const getRarityConfig = (score: number) => {
  if (score >= 90) return { label: 'GRAIL', color: 'bg-amber-500 text-black', border: 'border-amber-500', text: 'text-amber-400' };
  if (score >= 80) return { label: 'HYPE', color: 'bg-fuchsia-500 text-white', border: 'border-fuchsia-500', text: 'text-fuchsia-400' };
  if (score >= 60) return { label: 'LIMITED', color: 'bg-blue-500 text-white', border: 'border-blue-500', text: 'text-blue-400' };
  return { label: 'COMMON', color: 'bg-zinc-600 text-zinc-100', border: 'border-zinc-600', text: 'text-zinc-400' };
};
